### ISSUE TITLE
Check github/gitlab/... issue/pull request

### ISSUE THREAD

**Issue by guibou** [guibou/krank#1]
Krank can look for a github (or any other issue tracker really) links (issue or pull request) in the comment and check if they are closed / merged.

For example, a comment like that won't bitrot:

```
# This is a hack to mitigate https://github.com/foo/bar/issues/666
ugly = hack
```

Krank will tell you that the issue was closed and that it is time to remove the hack.

# Discussion

What happen if the github link is here for documentation and should stay even when the issue is merge / closed.

- Should we instead match on `TODO: link`? This is fine but introduces a custom marker.
- Should we add this link in krank ignore list?

**Comment by gbataille** [comment]
@guibou I propose we close that one since the base is there, I'll open a different issue for the Gitlab support
