### ISSUE TITLE
Report should print issue title

### ISSUE THREAD

**Issue by guibou** [guibou/krank#53]
Right now an issue is displayed like that:

```
hadrian/src/Settings/Packages.hs:205:30: error:
  now Closed: https://github.com/snowleopard/hadrian/issues/90
```

It can be really interesting if it was displayed with the issue title:

```
hadrian/src/Settings/Packages.hs:205:30: error:
  now Closed: https://github.com/snowleopard/hadrian/issues/90
  title: Cannot Build: compareSizes (rts missing _TRACE_gc and _TRACE_sched)
```

**Comment by gbataille** [comment]
<img width="563" alt="Screenshot 2020-04-26 at 10 28 42" src="https://user-images.githubusercontent.com/1113065/80302181-c6ee8f80-87a8-11ea-932c-c1551237acaf.png">
