### ISSUE TITLE
Hackage / Stackage release

### ISSUE THREAD

**Issue by guibou** [guibou/krank#70]
In https://github.com/NixOS/nixpkgs/pull/85178 user @nh2 suggested that we release a new version to hackage and one to stackage.

Since initial hackage release, we added:

- color output
- improved outputs (thank @gbataille)
- gitlab support! (thank @gbataille)
- the performance work (OMG, people from hackage are using the slow version of krank...)
- parrallel work (OMG bis. request are serialized. Users from hackage may have a really bad opinion about krank ;)
- ignore list (thank @gbataille)

I'll do that this week.

**Comment by guibou** [comment]
v0.2.0 is now on hackage.

However I cannot release krank on stackage:

```
[nix-shell:~/srcs/stackage/krank-0.2.0]$ rm -f stack.yaml && stack init --resolver nightly
Selected resolver: nightly-2020-04-18
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- ./

Selected resolver: nightly-2020-04-18
Selected resolver: nightly-2020-04-18
Resolver 'nightly-2020-04-18' does not have all the packages to match your requirements.
    pretty-terminal not found
        - krank requires -any
```

I do wonder if I need to push `pretty-terminal` to stackage too or if I need to find another library.

**Comment by nh2** [comment]
You can put it on Stackage. You don't need to be the author of a package to be its Stackage maintainer; it is common practice that when your dependency's author does not want to be its maintainer on Stackage themselves, you just become it yourself.

**Comment by guibou** [comment]
I love github linkage between projects. This issue will be closed by itself when it will be merged to stackage ;)

@nh2 do you think I still need to do the step to get `krank` in an `lts`? Considering that it is not a library, if user want to install it, they can just select the nightly snapshot and it will be fine.

**Comment by nh2** [comment]
> do you think I still need to do the step to get `krank` in an `lts`?

I certanly recommend it. Stackage runs CI that ensures that your package works with newer GHCs and the next Stackage LTS, thus guaranteeing that it'll work in the next LTS, library or not.

**Comment by guibou** [comment]
Looks like it was merged in stackage nightly. I'll do the paper work to have it in an lts.

**Comment by guibou** [comment]
- [x] stackage `nightly` release
- [x] stackage `lts` release

**Comment by guibou** [comment]
`krank` is part of `lts-16.3`
