### ISSUE TITLE
Please, add --version option

### ISSUE THREAD

**Issue by Anton-Latukha** [guibou/krank#81]
Self-explanatory.

Haskell devs can figure-out what version are they using from side sources, but users expect `--version` anyway now.

**Comment by guibou** [comment]
Really good point!

I don't know how I can do that automatically, but I'll do some research.

**Comment by Anton-Latukha** [comment]
I also didn't.

Still learning `optparse-applicative` they have, lets say, quite the documentation. Easier to learn from specs. (Modifiers/Arrtibutes -> Builders -> Parsers -> Parser composition -> Applicative -> Alternative -> Error handling -> Composing more complex cases) and then read the documentation. From my exp.

I also searched docs how to do the version. Needs to be looked at Haskell project sources.
It is probably:
  * or hardcoded
  * or during compilation takes info from cabal file
  * or from Git tag

**Comment by guibou** [comment]
> or hardcoded

I don't like that for obvious reason, But that's the simplest one.

> or during compilation takes info from cabal file

Yes, probably the best solution. However it won't track the intermediate builds.

> or from Git tag

Won't work for out of source build (i.e. from hackage / stack, ...)

So perhaps a mix between git tag and cabal file.

**Comment by Anton-Latukha** [comment]
More useful info:

https://github.com/pcapriotti/optparse-applicative/issues/389#issuecomment-633249468

So, logically, properly is to use: https://hackage.haskell.org/package/base-4.12.0.0/docs/Data-Version.html

**Comment by guibou** [comment]
@Anton-Latukha Thank you for the report. @gbataille Thank you for the code.
